export const apiUrls = {
    login: 'auth/login',
    refreshToken: 'auth/refresh',
    profile: 'auth/profile',
    brands: 'brands',
    createBrand: 'brands/create',
    salons: 'salons/filter',
    createSalon: 'salons/create',
    allSalons: 'salons/',
    editSalon: 'salons/edit',
    colors: 'global/colors',
    cities: 'global/cities',
    policy: 'global/policy',
    useOfWeb: 'global/useOfWeb',
    cookies: 'global/cookies',
    brand: 'brands/getBrand',
    getCoordinatesByAddress: 'json?address=',
    userProfile: 'auth/profile',
    twoFactorAuthCode: 'auth/2fa',
    sendTwoFactorAuthCode: 'auth/turnOnTwoFactorAuthentication',
    disabled2FA: 'auth/disabled2fa',
    sendGoogle2FACode: 'auth/googleAuth',
}
